{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Replace this file with your own hardware-configuration.nix
  # Generated by NixOS installer or nixos-generate-config
}
