source = ~/.config/hypr/configs/decoration.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/windowrules.conf

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = hyprlock
exec-once = blueman-applet
exec-once = hyprpaper
# exec-once = caelestia-shell

