# TODO: Finish hyprland.conf

# monitor=,preferred,auto,auto
monitor =,2560x1080@180,0x0,1

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprlock
exec-once = blueman-applet
exec-once = hyprpaper
exec-once = quickshell

input {
    kb_layout = us,ru
    kb_options = grp:win_space_toggle
    follow_mouse = 0

    sensitivity = -1
    accel_profile = flat
    force_no_accel = 1
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffff) rgba(00ff99ff) 45deg
    col.inactive_border = rgba(595959aa)

    # Force the core engine layout
    layout = dwindle
}

dwindle {
    force_split = 0
    preserve_split = true
    smart_split = false
}

decoration {
    rounding = 8

    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

animations {
    enabled = true;

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
}

# Keybinds
$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, W, killactive
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, thunar
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, B, exec, firefox
bind = $mainMod, P, pseudo,
bind = $mainMod, S, layoutmsg, togglesplit
bind = $mainMod, V, togglefloating
bind = $mainMod SHIFT, L, exec, hyprlock

# Fullscreen
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod, Print, exec, grim ~/Pictures/$(date +'%Y%m%d_%H%M%S_screenshot.png')
