input {
    kb_layout = us,ru
    kb_options = grp:win_space_toggle
    follow_mouse = 0

    sensitivity = -1
    accel_profile = flat
    force_no_accel = 1
}

$mainMod = SUPER

# General
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, W, killactive
bind = $mainMod, M, exit,

# Apps / commands
# bind = $mainMod ALT, L, exec, hyprlock
bind = $mainMod SHIFT, E, exec, kitty -e yazi
bind = $mainMod, B, exec, firefox
bind = $mainMod, E, exec, kitty --class yazi_floating -e yazi
bind = $mainMod, N, exec, kitty -e nvim
bind = $mainMod, T, exec, kitty --class tty_clock -e tty-clock
bind = $mainMod, P, pseudo,
bind = $mainMod, S, layoutmsg, togglesplit
bind = $mainMod, V, togglefloating

# Rofi
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod SHIFT, R, exec, rofi -show filebrowser
bind = $mainMod, Tab, exec, rofi -show window

# Fullscreen
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0

# Arrows
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod SHIFT, left, swapwindow, l
bind = $mainMod SHIFT, right, swapwindow, r
bind = $mainMod SHIFT, up, swapwindow, u
bind = $mainMod SHIFT, down, swapwindow, d

# Vim keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7

# Move to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7

# Mouse binds
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# WirePlumber / wpctl
bind=,XF86AudioMute,exec,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
binde=,XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binde=,XF86AudioRaiseVolume,exec,wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+

# Screenshots
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod, Print, exec, grim ~/Pictures/$(date +'%Y%m%d_%H%M%S_screenshot.png')

