windowrule {
  name = wr-kitty
  opacity = 0.97 0.85
  match:class = ^(kitty)$
}

windowrule {
  name = wr-yazi-floating
  float = on
  size = 1100 650
  center = on
  opacity = 0.95 0.85
  # dim_around = on
  match:class = ^(yazi_floating)$
}

windowrule {
  name = wr-loupe
  float = on
  center = on
  match:class = ^(loupe)$
}

windowrule {
  name = wr-mpv-fullscreen
  keep_aspect_ratio = on
  idle_inhibit = focus
  match:class = ^(mpv)$
}

windowrule {
  name = wr-clock
  float = on
  size = 420 220
  center = on
  match:class = ^(tty_clock)$
}
