general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffff) rgba(00ff99ff) 45deg
    col.inactive_border = rgba(595959aa)

    # Force the core engine layout
    layout = dwindle
}

dwindle {
    force_split = 0
    preserve_split = true
    smart_split = false
}

# Floating

windowrule {
  name = windowrule-yazi-floating
  float = on
  size = 1100 650
  center = on
  opacity = 0.95 0.85
  # dim_around = on
  match:class = ^(yazi_floating)$
}

windowrule {
  name = windowrule-loupe-floating
  float = on
  match:class = ^(loupe)$
}

windowrule {
  name = windowrule-thunar-copy
  float = on
  match:class = ^(thunar)$
  match:title = ^(File Operation Progress)$
}

windowrule {
  name = windowrule-clock
  float = on
  match:class = ^(terminal_clock)$
}

# Size & center

windowrule {
  name = windowrule-thunar
  size = 900 600
  match:class = ^(thunar)$
}

windowrule {
  name = windowrule-loupe
  center = on
  match:class = ^(loupe)$
}

# Blur & opacity

windowrule {
  name = windowrule-9
  opacity = 0.97 0.85
  match:class = ^(kitty)$
}
